package fish.philwants


object TestCredentials {
  // Test accounts
  val GENERIC_USERNAME_EMAIL = ???
  val GENERIC_USERNAME = ???
  val GENERIC_PASSWORD = ???

  val FACEBOOK_USERNAME = GENERIC_USERNAME_EMAIL
  val FACEBOOK_PASSWORD = GENERIC_PASSWORD

  val INSTAGRAM_USERNAME = GENERIC_USERNAME
  val INSTAGRAM_PASSWORD = GENERIC_PASSWORD

  val LINKEDIN_USERNAME = GENERIC_USERNAME_EMAIL
  val LINKEDIN_PASSWORD = GENERIC_PASSWORD

  val REDDIT_USERNAME = GENERIC_USERNAME
  val REDDIT_PASSWORD = GENERIC_PASSWORD

  val TWITTER_USERNAME = GENERIC_USERNAME_EMAIL
  val TWITTER_PASSWORD = GENERIC_PASSWORD

  val GITHUB_USERNAME = GENERIC_USERNAME
  val GITHUB_PASSWORD = GENERIC_PASSWORD

  val AMAZON_USERNAME = GENERIC_USERNAME
  val AMAZON_PASSWORD = GENERIC_PASSWORD

  val BAD_USERNAME_EMAIL = "shardtesting-bademail@gmail.com"
  val BAD_USERNAME = "shardtesting-badusername"
  val BAD_PASSWORD = "badpassword"

}
